library_ES_FR = {

    "COURS1": {

        "hola": "salut",
        "Cómo está usted?": "Comment allez-vous ?",
        "Qué tal?": "Comment ça va ?",
        "Cómo están ustedes?": "Comment allez-vous tous ?",
        "Cómo estás?": "Comment vas-tu ?",
        "Bien, gracias. Y tú?": "Bien, merci. Et toi ?",
        "Bien, gracias. Y ustedes?": "Bien, merci. Et vous tous ?",
        "Bien, gracias. Y usted?": "Bien, merci. Et vous ?",
        "bien": "bien",
        "regular": "comme-ci comme-ça",
        "Estoy bien": "Je vais bien.",
        "más o menos": "plus ou moins",
        "mal": "mal",
        "no muy bien": "pas très bien",
        "Estoy mal": "Je ne vais pas bien.",
        "buenos días": "bon matin",
        "buenas tardes": "bonne après-midi",
        "buen día": "bonjour",
        "buenas noches": "bonsoir, bonne nuit",
        "Me llamo": "Je m'appelle...",
        "Cómo te llamas?": "Comment tu t'appelles ?",
        "Soy": "Je suis",
        "Cómo se llama usted?": "Comment vous appelez-vous ?",
        "Mi nombre es": "Mon nom est",
        "mucho gusto": "ravi de vous rencontrer",
        "encantado": "enchanté",
        "Es un placer": "C'est un plaisir.",
        "encantada": "enchantée",
        "igualmente": "de même",
        "gracias": "merci",
        "muy bien, gracias": "très bien, merci",
        "muy": "très",
        "bastante bien": "plutôt bien",
        "bienvenidos": "bienvenue",
        "Le presento a": "Je vous présente à",
        "Te presento a": "Je te présente à",
        "Les presento a": "Je vous présente tous à",
        "adiós": "au revoir",
        "hasta mañana": "à demain",
        "chao": "chao",
        "hasta pronto": "à bientôt",
        "hasta luego": "à plus tard",
        "nos vemos": "à bientôt(cya)",
        "el curso": "le cours",
        "la lengua": "la langue",
        "los Estados Unidos": "les États-Unis",
        "el español": "l'espagnol",
        "el aspecto": "l'aspect",
        "la cultura": "la culture",
        "introductorio": "introductif",
        "importante": "important",
    },

    "COURS2": {

        "el": "le",
        "los": "les(h)",
        "la": "la",
        "las": "les(f)",
        "el libro": "le livre",
        "el sistema": "le système",
        "la mano": "la main",
        "la silla": "la chaise",
        "el mapa": "la carte",
        "la mesa": "la table",
        "el problema": "le problème",
        "la casa": "la maison",
        "la clase": "la classe",
        "el día": "le jour",
        "el reloj": "la montre",
        "el cuaderno": "le cahier",
        "el lápiz": "le crayon",
        "el agua": "l'eau",
        "la pared": "le mur",
        "la letra": "la lettre",
        "la música": "la musique",
        "el hotel": "l'hôtel",
        "el televisor": "la télévision",
        "la familia": "la famille",
        "el papel": "le papier",
        "interesante": "intéressant",
        "clásico": "classique",
        "popular": "populaire",
        "central": "central",
        "inteligente": "intelligent",
        "la educación": "l'éducation",
        "la libertad": "la liberté",
        "la nación": "la nation",
        "la posibilidad": "la possibilité",
        "la lección": "la leçon",
        "la actitud": "l'attitude",
        "la universidad": "l'université",
        "la virtud": "la vertu",
        "el pianista": "le pianiste",
        "la pianista": "la pianiste",
        "el señor": "le Monsieur",
        "la señora": "la Madame",
        "la señorita": "la Mademoiselle",
        "el profesor": "le professeur",
        "la profesora": "la professeur",
        "el dentista": "le dentiste",
        "la dentista": "la dentiste",
        "el futbolista": "le footballeur",
        "la futbolista": "la footballeuse",
        "el doctor": "le médecin",
        "la doctora": "la médecin",
        "el chico": "le garçon",
        "la chica": "la fille",
        "llamar": "appeler",
        "en": "dans",
        "hay": "il y a",
        "de": "de",
        "el norte": "le nord",
        "el oeste": "l'ouest",
        "el sur": "le sud",
        "el este": "l'est",
    },

    "COURS3": {

        "yo": "je",
        "él": "il",
        "tú": "tu",
        "ella": "elle",
        "usted": "vous [singulier, formel]",
        "nosotros": "nous [masculin]",
        "ustedes": "vous [pluriel, formel]",
        "nosotras": "nous [féminin]",
        "ellos": "ils",
        "vosotros": "vous [masculin pluriel, informel]",
        "ellas": "elles",
        "vosotras": "vous [féminin pluriel, informel]",
        "ser": "être",
        "Hablen!": "Parlez !",
        "No esperen!": "N'attendez pas !",
        "alto": "grand",
        "accidental": "accidentel",
        "simpático": "sympathique",
        "usual": "habituel",
        "antipático": "antipathique",
        "normal": "normal",
        "guapo": "beau",
        "optimista": "optimiste",
        "bonito": "joli",
        "pesimista": "pessimiste",
        "feo": "moche",
        "activo": "actif",
        "joven": "jeune",
        "responsable": "responsable",
        "viejo": "vieux",
        "largo": "long",
        "embarazada": "enceinte",
        "corto": "court",
        "elegante": "élégant",
        "grande": "grand",
        "excelente": "excellent",
        "pequeño": "petit",
        "fantástico": "fantastique",
        "avergonzado": "gêné",
        "el accidente": "l'accident",
        "el taxi": "le taxi",
        "la cuestión": "la question, le problème",
        "el teléfono": "le téléphone",
        "la pregunta": "la question",
        "el colegio": "le lycée",
        "la persona": "la personne",
        "el amigo": "l'ami",
        "el vecino": "le voisin",
        "la amiga": "l'amie",
        "la vecina": "la voisine",
        "el novio": "le petit ami",
        "el hombre": "l'homme",
        "la novia": "la petite amie",
        "la mujer": "la femme",
        "y": "et",
        "sí": "oui",
        "o": "ou",
        "no": "non",
        "pero": "mais",
        "ahora": "maintenant",

        "moreno": "brun",
        "rubio": "blond",
        "flaco": "mince",
        "gordo": "gros",
        "alto": "haut",
        "bajo": "bas",
        "gracioso": "drôle",
        "comico": "comique",
        "serio": "serieux",
        "ambicioso": "ambitieux",
        "parezoso": "paresseux",
        "honesto": "honnête",
        "generoso": "genereux",
        "cansado": "fatigué",
    },

    "COURS4": {

        "cubano": "cubain",
        "venezolano": "vénézuélien",
        "dominicano": "dominicain",
        "colombiano": "colombien",
        "puertorriqueño": "portoricain",
        "ecuatoriano": "équatorien",
        "norteamericano": "américain (du Nord)",
        "peruano": "péruvien",
        "mexicano": "mexicain",
        "boliviano": "bolivien",
        "guatemalteco": "guatémaltèque",
        "chileno": "chilien",
        "salvadoreño": "salvadorien",
        "paraguayo": "paraguayen",
        "hondureño": "hondurien",
        "argentino": "argentin",
        "nicaragüense": "nicaraguayen",
        "uruguayo": "uruguayen",
        "costarricense": "costaricien",
        "español": "espagnol",
        "panameño": "panaméen",
        "ecuatoguineano": "équato-guinéen",
        "el café": "le café",
        "el trabajador": "le travailleur",
        "hablar": "parler",
        "trabajar": "travailler",
        "bailar": "danser",
        "llegar": "arriver",
        "tomar": "prendre, boire",
        "estudiar": "étudier",
        "ayudar": "aider",
        "cantar": "chanter",
        "comprar": "acheter",
        "cocinar": "cuisiner",
        "preparar": "préparer",
        "indicar": "indiquer",
        "escuchar": "écouter",
        "ordenar": "ordonner",
        "viajar": "voyager",
        "dedicar": "dédier",
        "fuerte": "fort",
        "contento": "content",
        "egoísta": "égoïste",
        "famoso": "célèbre",
        "trabajador": "travailleur",
        "formal": "formel",
        "hablador": "bavard",
        "informal": "informel",
        "ideal": "idéal",
        "bueno": "bon",
        "tímido": "timide",
        "malo": "mauvais",
        "terrible": "terrible",
        "mucho": "beaucoup",
        "fenomenal": "phénoménal",
        "muchos": "beaucoup",
        "paciente": "patient",
        "poco": "peu",
        "impaciente": "impatient",
        "pocos": "peu (few)",
    },

    "COURS5": {

        "un": "un",
        "unos": "des(h)",
        "una": "une",
        "unas": "des(f)",
        "el estudiante": "l'étudiant",
        "el béisbol": "le baseball",
        "la estudiante": "l'étudiante",
        "el examen": "l'examen",
        "el águila": "l'aigle",
        "el kilómetro": "le kilomètre",
        "el zapato": "la chaussure",
        "el kilo": "le kilo",
        "el deporte": "le sport",
        "la cerveza": "la bière",
        "católico": "catholique",
        "extra": "supplémentaire",
        "enseñar": "enseigner",
        "mirar": "regarder",
        "caminar": "marcher",
        "llevar": "porter, emporter",
        "buscar": "chercher",
        "necesitar": "avoir besoin de",
        "cuánto/a?": "combien ?",
        "para": "pour",
        "cuántos/as?": "combien de ?",
        "por favor": "s'il vous plaît",
        "cero": "zéro",
        "seis": "six",
        "uno": "un",
        "siete": "sept",
        "dos": "deux",
        "ocho": "huit",
        "tres": "trois",
        "nueve": "neuf",
        "cuatro": "quatre",
        "diez": "dix",
        "cinco": "cinq",
        "once": "onze",
        "doce": "douze",
        "trece": "treize",
        "catorce": "quatorze",
        "quince": "quinze",
        "dieciséis": "seize",
        "diecisiete": "dix-sept",
        "dieciocho": "dix-huit",
        "diecinueve": "dix-neuf",
        "veinte": "vingt",
        "treinta": "trente",
        "setenta": "soixante-dix",
        "cuarenta": "quarante",
        "ochenta": "quatre-vingts",
        "cincuenta": "cinquante",
        "noventa": "quatre-vingt-dix",
        "sesenta": "soixante",
        "cien": "cent",
    },


    "VERBES BASE": {

        "ir": "aller",
        "poder": "pouvoir",
        "saber": "savoir",
        "decir": "dire",
        "venir": "venir",
        "hablar": "parler",
        "escribir": "écrire",
        "vivir": "vivre",
        "ser": "être",
        "estar": "être (temporaire)",
        "vestir": "habiller",
        "llevar": "porter",
        "tener": "avoir",
        "ayudar": "aider",
        "comer": "manger",
        "hacer": "faire",

    },

    "VERBES": {

#ETRE PRESENT
        "ser": "être",
        "soy": "je suis",
        "eres": "tu es",
        "es": "il/elle/on est",
        "somos": "nous sommes",
        "sois": "vous êtes",
        "son": "ils/elles sont",

#ETRE (TEMPORAIRE) PRESENT
        "estar": "être (temporaire)",
        "estoy": "je suis (temporaire)",
        "estás": "tu es (temporaire)",
        "está": "il est (temporaire)",
        "estamos": "nous sommes (temporaire)",
        "estáis": "vous êtes (temporaire)",
        "están": "ils sont (temporaire)",

#AVOIR PRESENT
        "tener": "avoir",
        "tengo": "j'ai",
        "tienes": "tu as",
        "tiene": "il a",
        "tenemos": "nous avons",
        "tenéis": "vous avez",
        "tienen": "ils ont",

#AIDER PRESENT
        "ayudar": "aider",
        "ayudo": "j'aide",
        "ayudas": "tu aides",
        "ayuda": "il aide",
        "ayudamos": "nous aidons",
        "ayudáis": "vous aidez",
        "ayudan": "ils aident",

#MANGER PRESENT
        "comer": "manger",
        "como": "je mange",
        "comes": "tu manges",
        "come": "il mange",
        "comemos": "nous mangeons",
        "coméis": "vous mangez",
        "comen": "ils mangent",

#PORTER PRESENT
        "llevar": "porter",
        "llevo": "je porte",
        "llevas": "tu portes",
        "lleva": "il porte",
        "llevamos": "nous portons",
        "lleváis": "vous portez",
        "llevan": "ils portent",

#PORTER (VETEMENT) PRESENT
        "vestir": "porter (vêtement)",
        "visto": "je porte (vêtement)",
        "vistes": "tu portes (vêtement)",
        "viste": "il porte (vêtement)",
        "vestimos": "nous portons (vêtement)",
        "vestís": "vous portez (vêtement)",
        "visten": "ils portent (vêtement)",


#FAIRE PRESENT
        "hacer": "faire",
        "hago": "je fais",
        "haces": "tu fais",
        "hace": "il/elle/on fait",
        "hacemos": "nous faisons",
        "hacéis": "vous faites",
        "hacen": "ils/elles font",

#ALLER PRESENT

        "ir": "aller",
        "voy": "je vais",
        "vas": "tu vas",
        "va": "il/elle/on va",
        "vamos": "nous allons",
        "vais": "vous allez",
        "van": "ils/elles vont",

#POUVOIR PRESENT
        "poder": "pouvoir",
        "puedo": "je peux",
        "puedes": "tu peux",
        "puede": "il/elle/on peut",
        "podemos": "nous pouvons",
        "podéis": "vous pouvez",
        "pueden": "ils/elles peuvent",

#SAVOIR PRESENT
        "saber": "savoir",
        "sé": "je sais",
        "sabes": "tu sais",
        "sabe": "il/elle/on sait",
        "sabemos": "nous savons",
        "sabéis": "vous savez",
        "saben": "ils/elles savent",

#DIRE PRESENT
        "decir": "dire",
        "digo": "je dis",
        "dices": "tu dis",
        "dice": "il/elle/on dit",
        "decimos": "nous disons",
        "decís": "vous dites",
        "dicen": "ils/elles disent",

#VENIR PRESENT
        "venir": "venir",
        "vengo": "je viens",
        "vienes": "tu viens",
        "viene": "il/elle/on vient",
        "venimos": "nous venons",
        "venís": "vous venez",
        "vienen": "ils/elles viennent",

#PARLER PRESENT
        "hablar": "parler",
        "hablo": "je parle",
        "hablas": "tu parles",
        "habla": "il/elle/on parle",
        "hablamos": "nous parlons",
        "habláis": "vous parlez",
        "hablan": "ils/elles parlent",

#ECRIRE PRESENT
        "escribir": "écrire",
        "escribo": "j'écris",
        "escribes": "tu écris",
        "escribe": "il/elle/on écrit",
        "escribimos": "nous écrivons",
        "escribís": "vous écrivez",
        "escriben": "ils/elles écrivent",

#VIVRE PRESENT
        "vivir": "vivre",
        "vivo": "je vis",
        "vives": "tu vis",
        "vive": "il/elle/on vit",
        "vivimos": "nous vivons",
        "vivís": "vous vivez",
        "viven": "ils/elles vivent",
    },

}
